// Regenerates src/abis.ts from the Foundry build output (run `forge build` in the repo root first).
// The ABIs are the single source of truth for the SDK: if a contract changes, rerun this and the
// type checker will point at every call site that no longer matches.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const abi = (file, name) => JSON.parse(readFileSync(join(root, "out", file, `${name}.json`), "utf8")).abi;

// ERC-8004 functions the canonical registries expose beyond the subset the contracts call.
// Signatures checked against the live Monad testnet deployments (0x8004A818… / 0x8004B663…).
const identityExtra = [
  { type: "function", name: "tokenURI", stateMutability: "view", inputs: [{ name: "tokenId", type: "uint256" }], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "owner", type: "address" }], outputs: [{ name: "", type: "uint256" }] },
];
const reputationExtra = [
  {
    type: "function", name: "getSummary", stateMutability: "view",
    inputs: [{ name: "agentId", type: "uint256" }, { name: "clientAddresses", type: "address[]" }, { name: "tag1", type: "string" }, { name: "tag2", type: "string" }],
    outputs: [{ name: "count", type: "uint64" }, { name: "summaryValue", type: "int128" }, { name: "summaryValueDecimals", type: "uint8" }],
  },
  {
    type: "function", name: "readAllFeedback", stateMutability: "view",
    inputs: [{ name: "agentId", type: "uint256" }, { name: "clientAddresses", type: "address[]" }, { name: "tag1", type: "string" }, { name: "tag2", type: "string" }, { name: "includeRevoked", type: "bool" }],
    outputs: [
      { name: "clients", type: "address[]" }, { name: "feedbackIndexes", type: "uint64[]" }, { name: "values", type: "int128[]" },
      { name: "valueDecimals", type: "uint8[]" }, { name: "tag1s", type: "string[]" }, { name: "tag2s", type: "string[]" }, { name: "revokedStatuses", type: "bool[]" },
    ],
  },
];
const usdcExtra = [
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "version", stateMutability: "view", inputs: [], outputs: [{ name: "", type: "string" }] },
  { type: "function", name: "authorizationState", stateMutability: "view", inputs: [{ name: "authorizer", type: "address" }, { name: "nonce", type: "bytes32" }], outputs: [{ name: "", type: "bool" }] },
];

const out = {
  agentPassportAbi: abi("AgentPassport.sol", "AgentPassport"),
  jobEscrowAbi: abi("JobEscrow.sol", "JobEscrow"),
  identityRegistryAbi: [...abi("IERC8004.sol", "IIdentityRegistry"), ...identityExtra],
  reputationRegistryAbi: [...abi("IERC8004.sol", "IReputationRegistry"), ...reputationExtra],
  usdcAbi: [...abi("IERC20.sol", "IERC20"), ...abi("IERC20.sol", "IERC3009"), ...usdcExtra],
};

let ts = "// GENERATED by scripts/gen-abis.mjs from the Foundry build output. Do not edit by hand.\n";
for (const [name, value] of Object.entries(out)) ts += `\nexport const ${name} = ${JSON.stringify(value, null, 2)} as const;\n`;
writeFileSync(join(root, "sdk", "src", "abis.ts"), ts);
console.log("wrote src/abis.ts:", Object.entries(out).map(([k, v]) => `${k}(${v.length})`).join(" "));
